# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\imc3v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(701, 402)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setAutoFillBackground(False)
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(40, 190, 221, 42))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setTextFormat(QtCore.Qt.PlainText)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(40, 100, 181, 42))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setTextFormat(QtCore.Qt.PlainText)
        self.label3.setObjectName("label3")
        self.peso = QtWidgets.QLineEdit(Dialog)
        self.peso.setGeometry(QtCore.QRect(280, 90, 401, 70))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setItalic(False)
        self.peso.setFont(font)
        self.peso.setInputMethodHints(QtCore.Qt.ImhNone)
        self.peso.setText("")
        self.peso.setFrame(True)
        self.peso.setClearButtonEnabled(True)
        self.peso.setObjectName("peso")
        self.altura = QtWidgets.QLineEdit(Dialog)
        self.altura.setGeometry(QtCore.QRect(280, 174, 401, 67))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.altura.setFont(font)
        self.altura.setText("")
        self.altura.setClearButtonEnabled(True)
        self.altura.setObjectName("altura")
        self.label4 = QtWidgets.QLabel(Dialog)
        self.label4.setGeometry(QtCore.QRect(270, 320, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setTextFormat(QtCore.Qt.PlainText)
        self.label4.setObjectName("label4")
        self.button = QtWidgets.QPushButton(Dialog)
        self.button.setGeometry(QtCore.QRect(30, 310, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(40, 11, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.resultado = QtWidgets.QTextEdit(Dialog)
        self.resultado.setGeometry(QtCore.QRect(523, 310, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setItalic(False)
        self.resultado.setFont(font)
        self.resultado.setObjectName("resultado")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.button.clicked.connect(self.IMC)
        
    def IMC(self):
        peso = float(self.peso.text())
        altura = float(self.altura.text()) / 100
        imc = peso / (altura ** 2)
        # print(imc)
        self.resultado.setText(str(round(imc, 2)))
        
        if imc < 18.5:
            self.resultado.setStyleSheet('background: Yellow')
        elif imc < 25:
            self.resultado.setStyleSheet('background: Green')
        elif imc < 30:
            self.resultado.setStyleSheet('background: Orange')
        else:
            self.resultado.setStyleSheet('background: Red')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculadora IMC "))
        self.label2.setText(_translate("Dialog", "Altura (cm)"))
        self.label3.setText(_translate("Dialog", "Peso (kg)"))
        self.label4.setText(_translate("Dialog", "IMC (kg/m²) = "))
        self.button.setText(_translate("Dialog", "Calcular"))
        self.label1.setText(_translate("Dialog", "Calculadora Índice de Massa Corporal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
